version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: yLukas077
      POSTGRES_PASSWORD: deliveryunicap
      POSTGRES_DB: deliverydata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
